// Embeds templates and the package version into src/generated/assets.ts so the compiled binary
// reads nothing from the package folder at runtime (7.1).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8");
const dir = (rel) =>
  Object.fromEntries(
    fs
      .readdirSync(path.join(root, rel))
      .filter((f) => f.endsWith(".md"))
      .sort()
      .map((f) => [f.replace(/\.md$/, ""), read(path.join(rel, f))]),
  );

const out = `// Generated by scripts/embed-assets.mjs. Do not edit.
export const VERSION = ${JSON.stringify(pkg.version)};
export const COMMAND_TEMPLATES: Record<string, string> = ${JSON.stringify(dir("templates/commands"), null, 2)};
export const SPEC_TEMPLATES: Record<string, string> = ${JSON.stringify(dir("templates/spec"), null, 2)};
`;
fs.mkdirSync(path.join(root, "src/generated"), { recursive: true });
const target = path.join(root, "src/generated/assets.ts");
if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== out) fs.writeFileSync(target, out);
